{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.storage.claim.name }}
  labels:
    app.kubernetes.io/name: {{ include "inbucket.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "inbucket.chart" . }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "{{ .Values.storage.claim.size }}"
  storageClassName: {{ .Values.storage.claim.class }}
{{- end }}
